%YAML:1.0

#common parameters
#support: 1 imu 1 cam; 1 imu 2 cam: 2 cam; 
imu: 0         
num_of_cam: 1

imu_topic: "/mavros/imu/data"
image0_topic: "/camera/infra1/image_rect_raw"

# output_path: ""
mapping_time_log_path: "/home/nv/Desktop/loop_output/dld_rs_ref7_mappT.txt"

cam0_calib: "rs.yaml"

image_width: 640
image_height: 480

#feature traker paprameters
max_cnt: 200            # max feature number in feature tracking
min_dist: 10            # min distance between two features 
min_dist_lidarpt: 20 
freq: 10                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 0           # publish tracking image as topic
flow_back: 1            # perform forward and backward optical flow to improve feature tracking accuracy



#loop closure parameters
mapping_mode: 0 #0 lidar only;  1 vision only ; 2 lidar+vision
build_keyframe: 1               # build keyframe for loop closure
load_previous_pose_graph: 0        # load and reuse previous pose graph; load from 'pose_graph_save_path'
pose_graph_save_path: "/home/nv/Desktop/loop_output/keyframes_dld_rs_ref7/" # save and load path
debug_image: 1                   # save image in pose graph for visualization prupose; you can close this function by setting 0 
show_track: 0           # publish tracking image as topic
# skip_dist: 1.0
mapp_dis_factor: 800


#! test on 2024.4.5

# body_T_cam0: !!opencv-matrix
#    rows: 4
#    cols: 4
#    dt: d
#    data: [ 0., 0., 1., 5.0000000000000003e-02, -1., 0., 0.,
#        2.5000000000000001e-02, 0., -1., 0., -2.0000000000000000e-02, 0.,
#        0., 0., 1. ]
# body_T_cam1: !!opencv-matrix
#    rows: 4
#    cols: 4
#    dt: d
#    data: [ 0., 0., 1., 5.0000000000000003e-02, -1., 0., 0.,
#        -2.4916000000000001e-02, 0., -1., 0., -2.0000000000000000e-02, 0.,
#        0., 0., 1. ]

#! test on 2024.4.5

body_T_cam0: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [ -7.9409474578031169e-03, -2.0129909406697899e-02,
       9.9976537707136659e-01, 9.9000000000000005e-02,
       -9.9996700000000005e-01, 1.8944999999999999e-03,
       -7.9041900000000002e-03, 2.5000000000000008e-02,
       -1.7357150206763865e-03, -9.9979521923657899e-01,
       -2.0144689300393537e-02, 3.4000000000000002e-02, 0., 0., 0., 1. ]
body_T_cam1: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [ -7.9409474578031169e-03, -2.0129909406697899e-02,
       9.9976537707136659e-01, 9.9000000000000005e-02,
       -9.9996700000000005e-01, 1.8944999999999999e-03,
       -7.9041900000000002e-03, -2.5000000000000008e-02,
       -1.7357150206763865e-03, -9.9979521923657899e-01,
       -2.0144689300393537e-02, 3.4000000000000002e-02, 0., 0., 0., 1. ]

